UPlant/Models/DB/InterventiAlberi.cs
using System;
using System.Collections.Generic;

namespace UPlant.Models.DB;

public partial class InterventiAlberi
{
    public Guid id { get; set; }

    public Guid individuo { get; set; }

    public DateTime dataapertura { get; set; }

    public Guid priorita { get; set; }

    public Guid intervento { get; set; }

    public Guid fornitore { get; set; }

    public string motivo { get; set; }

    public string esitointervento { get; set; }

    public bool statoIntervento { get; set; }

    public DateTime? dataultimamodifica { get; set; }

    public Guid utenteapertura { get; set; }

    public Guid utenteultimamodifica { get; set; }

    public Guid statoIndividuo { get; set; }

    public Guid condizione { get; set; }

    public virtual Condizioni condizioneNavigation { get; set; }

    public virtual Fornitori fornitoreNavigation { get; set; }

    public virtual Individui individuoNavigation { get; set; }

    public virtual TipoInterventiAlberi interventoNavigation { get; set; }

    public virtual TipoPrioritaAlberi prioritaNavigation { get; set; }

    public virtual StatoIndividuo statoIndividuoNavigation { get; set; }

    public virtual Users utenteaperturaNavigation { get; set; }

    public virtual Users utenteultimamodificaNavigation { get; set; }
}

UPlant/Controllers/InterventiAlberiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UPlant.Models;
using UPlant.Models.DB;


namespace UPlant.Controllers
{
    [Authorize(Roles = "Administrator,Tree")]
    public class InterventiAlberiController : BaseController
    {
        private readonly Entities _context;
        private readonly LanguageService _languageService;
        public InterventiAlberiController(Entities context, LanguageService languageService)
        {
            _context = context;
            _languageService = languageService;
        }

        // GET: Alberi
        public async Task<IActionResult> Index()
        {

         

            var flat = await _context.InterventiAlberi
     .Select(a => new
     {
         a.id,                      // <-- PK Alberi (cambia se diverso)
         a.individuo,
         a.statoIntervento,                   // false = aperto
         a.dataultimamodifica,
         livello = a.prioritaNavigation.livello  // 0..5 dalla tabella TipoPrioritaAlberi
     })
     .ToListAsync();

            // Raggruppo e scelgo la riga migliore per ogni individuo
            var bestPerIndividuo = flat
                .GroupBy(x => x.individuo)
                .Select(g =>
                {
                    var hasOpen = g.Any(x => x.statoIntervento == false);

                    var best = g
                        .OrderByDescending(x => x.statoIntervento == false) // aperti prima
                        .ThenByDescending(x => x.livello)                   // 0 più alta
                        .ThenByDescending(x => x.dataultimamodifica)
                        .First();

                    return new
                    {
                        Individuo = g.Key,
                        HasOpen = hasOpen,
                        BestId = best.id,
                        BestLivello = best.livello,
                        BestData = best.dataultimamodifica
                    };
                })
                .OrderByDescending(x => x.HasOpen)     // individui con aperti prima
                .ThenByDescending(x => x.BestLivello)            // livello 0 prima
                .ThenByDescending(x => x.BestData)     // ultima modifica più recente
                .ToList();

            var bestIds = bestPerIndividuo.Select(x => x.BestId).ToList();


            // PASSO 2: carico SOLO le righe "best" con tutte le Include che servono
            var entities = await _context.InterventiAlberi
                .Where(a => bestIds.Contains(a.id))    // <-- PK Alberi (cambia se diverso)
                .Include(a => a.fornitoreNavigation)
                .Include(a => a.interventoNavigation)
                .Include(a => a.prioritaNavigation)
                .Include(a => a.utenteaperturaNavigation)
                .Include(a => a.utenteultimamodificaNavigation)
                .Include(a => a.individuoNavigation).ThenInclude(i => i.StoricoIndividuo).ThenInclude(s => s.statoIndividuoNavigation)
                .Include(a => a.individuoNavigation).ThenInclude(i => i.StoricoIndividuo).ThenInclude(s => s.condizioneNavigation)
                .Include(a => a.individuoNavigation).ThenInclude(i => i.accessioneNavigation).ThenInclude(s => s.specieNavigation)
                .Include(a => a.individuoNavigation).ThenInclude(i => i.collezioneNavigation).ThenInclude(c => c.settoreNavigation)
                .ToListAsync();

            // Contains() non preserva l'ordine: riordino come bestPerIndividuo
            var order = bestPerIndividuo
                .Select((x, idx) => new { x.BestId, idx })
                .ToDictionary(x => x.BestId, x => x.idx);

            entities = entities.OrderBy(e => order[e.id]).ToList(); // <-- PK Alberi (cambia se diverso)

            return View(entities);
        }

        // GET: Alberi/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alberi = await _context.InterventiAlberi
                .Include(a => a.fornitoreNavigation)
                .Include(a => a.individuoNavigation).ThenInclude(i => i.StoricoIndividuo).ThenInclude(s => s.statoIndividuoNavigation)
                .Include(a => a.individuoNavigation).ThenInclude(i => i.StoricoIndividuo).ThenInclude(s => s.condizioneNavigation)
                .Include(a => a.individuoNavigation)
                .Include(a => a.interventoNavigation)
                .Include(a => a.prioritaNavigation)
                .Include(a => a.utenteaperturaNavigation)
                .Include(a => a.utenteultimamodificaNavigation)
                .FirstOrDefaultAsync(m => m.id == id);
            if (alberi == null)
            {
                return NotFound();
            }

            return View(alberi);
        }

        // GET: Alberi/Create
        public IActionResult Create(Guid idindividuo)
        {
            var linguacorrente = _languageService.GetCurrentCulture();
            var individuo = _context.Individui
                  .Include(i => i.StoricoIndividuo).ThenInclude(s => s.statoIndividuoNavigation)
                .Include(i => i.StoricoIndividuo).ThenInclude(s => s.condizioneNavigation)
               .Include(s => s.accessioneNavigation)
               .ThenInclude(x => x.specieNavigation)
               .FirstOrDefault(x => x.id == idindividuo);


            string username = User.Identities.FirstOrDefault()?.Claims?.Where(c => c.Type == "UnipiUserID").FirstOrDefault()?.Value;
            var oggettoutente = _context.Users.Where(a => a.UnipiUserName == (username).Substring(0, username.IndexOf("@")));


            Guid organizzazione = oggettoutente.Select(a => a.Organizzazione).FirstOrDefault();
            Guid utente = oggettoutente.Select(a => a.Id).FirstOrDefault();
            var lastStorico = individuo.StoricoIndividuo.OrderByDescending(s => s.dataInserimento).FirstOrDefault();
            var selectedStato = lastStorico?.statoIndividuo;
            var selectedCondizione = lastStorico?.condizione;
            ViewData["progressivo"] = individuo.progressivo;
            ViewData["utenteapertura"] = utente;
            ViewData["utenteultimamodifica"] = utente;
            ViewData["fornitore"] = new SelectList(_context.Fornitori, "id", "descrizione");
            ViewData["individuo"] = individuo.id;
            ViewData["nomescientifico"] = individuo.accessioneNavigation.specieNavigation.nome_scientifico;
            if (linguacorrente == "en-US")
            {


                ViewData["statoIndividuo"] = new SelectList(_context.StatoIndividuo.Select(x => new { x.id, Desc = string.IsNullOrEmpty(x.descrizione_en) ? x.stato : x.descrizione_en }), "id", "Desc", selectedStato);
                ViewData["condizione"] = new SelectList(_context.Condizioni.Select(x => new { x.id, Desc = string.IsNullOrEmpty(x.descrizione_en) ? x.condizione : x.descrizione_en }), "id", "Desc", selectedCondizione);
                ViewData["intervento"] = new SelectList(_context.TipoInterventiAlberi.OrderByDescending(a => a.ordinamento).Select(a => new { a.id, Desc = string.IsNullOrEmpty(a.descrizione_en) ? a.descrizione : a.descrizione_en }), "id", "Desc");
                ViewData["priorita"] = new SelectList(_context.TipoPrioritaAlberi.OrderByDescending(a => a.ordinamento).Select(a => new { a.id, Desc = string.IsNullOrEmpty(a.descrizione_en) ? a.descrizione : a.descrizione_en }), "id", "Desc");
            }

            else
            {
                ViewData["statoIndividuo"] = new SelectList(_context.StatoIndividuo.OrderByDescending(a => a.ordinamento), "id", "stato", selectedStato);
                ViewData["condizione"] = new SelectList(_context.Condizioni.OrderByDescending(a => a.ordinamento), "id", "condizione", selectedCondizione);
                ViewData["intervento"] = new SelectList(_context.TipoInterventiAlberi.OrderByDescending(a => a.ordinamento), "id", "descrizione");
                ViewData["priorita"] = new SelectList(_context.TipoPrioritaAlberi.OrderByDescending(a => a.ordinamento), "id", "descrizione");
            }
            return View();
        }

        // POST: Alberi/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,individuo,dataapertura,priorita,intervento,fornitore,motivo,esitointervento,statoIntervento,dataultimamodifica,utenteapertura,utenteultimamodifica,statoIndividuo,condizione")] InterventiAlberi interventiAlberi)
        {
            var linguacorrente = _languageService.GetCurrentCulture();
            if (ModelState.IsValid)
            {
                interventiAlberi.dataapertura = DateTime.Now;
                interventiAlberi.id = Guid.NewGuid();
                interventiAlberi.dataultimamodifica = DateTime.Now;
                interventiAlberi.statoIntervento = false; // aperto di default
                _context.Add(interventiAlberi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            var selectedStato = interventiAlberi.statoIndividuo;
            var selectedCondizione = interventiAlberi.condizione;
            ViewData["fornitore"] = new SelectList(_context.Fornitori, "id", "descrizione", interventiAlberi.fornitore);
            ViewData["individuo"] = new SelectList(_context.Individui, "id", "progressivo", interventiAlberi.individuo);
            ViewData["utenteapertura"] = new SelectList(_context.Users, "Id", "CF", interventiAlberi.utenteapertura);

UPlant/Views/InterventiAlberi/Create.cshtml
@model UPlant.Models.DB.InterventiAlberi
@inject LanguageService language
@{
    ViewBag.Title = @language.Getkey("Global_Individual");
}

<p>
    <a asp-action="Index" asp-controller="InterventiAlberi">
        <span class="btn btn btn-info " title="@language.Getkey("Global_Go_Back")">
            @language.Getkey("Global_Go_Back")
        </span>
    </a>
</p>

<div class="col-lg-12">
    <div class="card card-primary">
        <div class="card-header with-border">
            <h3 class="card-title font-weight-bold">
                @language.Getkey("Shared_Comp_Sb_Tree") - @language.Getkey("Global_Individual") : @(ViewData["progressivo"] ?? "")
                <span> - </span> @language.Getkey("Global_Species")@Html.Label(" :  ") @(ViewData["nomescientifico"] ?? "")
            </h3>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="card-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <input asp-for="individuo" type="hidden" value="@(ViewData["individuo"] ?? Guid.Empty)" />
                    <input asp-for="utenteapertura" type="hidden" value="@(ViewData["utenteapertura"] ?? null)" />
                    <input asp-for="utenteultimamodifica" type="hidden" value="@(ViewData["utenteultimamodifica"] ?? null)" />
                </div>

                <div class="row">
                

                    <div class="form-group col">
                        <label asp-for="priorita" class="control-label">@language.Getkey("Global_Tree_Priority")</label>
                        <select asp-for="priorita" class="form-control" asp-items="ViewBag.priorita"></select>
                    </div>

                   
                </div>
                <div class="row">
                    <div class="form-group col">
                        <label asp-for="intervento" class="control-label"></label>
                        <select asp-for="intervento" class="form-control" asp-items="ViewBag.intervento"></select>
                    </div>
                    <div class="form-group col">
                        <label asp-for="fornitore" class="control-label"></label>
                        <select asp-for="fornitore" class="form-control" asp-items="ViewBag.fornitore"></select>
                    </div>
                </div>
                <hr />
                <div class="row text-center font-weight-bold">Dettagli</div>
                <hr />

                <div class="row">
                    

                    <div class="form-group col">
                        <label asp-for="motivo" class="control-label"></label>
                        <input asp-for="motivo" class="form-control" />
                        <span asp-validation-for="motivo" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <!-- NUOVE DROPDOWN: Stato Individuo e Condizione -->
                    <div class="form-group col">
                        <label class="control-label">@language.Getkey("Global_Individual_Status")</label>
                        <!-- uso name/id espliciti: funzionerà anche se il model non ha la proprietà -->
                        <select id="statoIndividuo" name="statoIndividuo" class="form-control select2"
                                asp-items="@(ViewData["statoIndividuo"] as SelectList)"></select>
                    </div>

                    <div class="form-group col">
                        <label class="control-label">@language.Getkey("Global_Condition")</label>
                        <select id="condizione" name="condizione" class="form-control select2"
                                asp-items="@(ViewData["condizione"] as SelectList)"></select>
                    </div>
                </div>

                <hr />
                <div class="form-group">
                    <input type="submit" value="@language.Getkey("Global_Add")" class="btn btn-primary" />
                </div>
            </div>
        }

    </div>

    <p>
        <a asp-action="Index" asp-controller="InterventiAlberi">
            <span class="btn btn btn-info " title="@language.Getkey("Global_Go_Back")">
                @language.Getkey("Global_Go_Back")
            </span>
        </a>
    </p>
</div>

@section Styles {
    <link href="~/css/select2.min.css" rel="stylesheet" />
}

@section Scripts {
    <script src="~/js/select2.min.js"></script>
    <script src="~/js/jquery.validation.min.js"></script>
}

@section CustomScripts {
    <script>
        $(function () {
            // inizializza Select2 sulle due select (se presente)
            if ($.fn.select2) {
                $('.select2').select2({
                    width: '100%',
                    theme: 'bootstrap4' // se usi la integrazione bootstrap per Select2; altrimenti rimuovi
                });
            }

            // Se vuoi puoi forzare la selezione iniziale dal SelectList (già gestito da asp-items con selected)
            // es: $('#statoIndividuo').val('@ViewData["statoIndividuoSelected"]')...

        });
    </script>
}

UPlant/Views/InterventiAlberi/Delete.cshtml
@model UPlant.Models.DB.InterventiAlberi

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alberi</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dataapertura)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dataapertura)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.motivo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.motivo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.esitointervento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.esitointervento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.statoIntervento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.statoIntervento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dataultimamodifica)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.dataultimamodifica)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.fornitoreNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.fornitoreNavigation.descrizione)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.individuoNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.individuoNavigation.progressivo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.interventoNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.interventoNavigation.descrizione)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.prioritaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.prioritaNavigation.descrizione)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.utenteaperturaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.utenteaperturaNavigation.CF)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.utenteultimamodificaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.utenteultimamodificaNavigation.CF)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

UPlant/Views/InterventiAlberi/Details.cshtml
@model UPlant.Models.DB.InterventiAlberi
@inject LanguageService language
@{
    ViewBag.Title = language.Getkey("Global_Tree");
    ViewBag.lang = language.GetCurrentCulture();
}



<div class="card card-outline card-primary">
    <div class="card-header with-border">

        <div class="card-body">
            <div class="row">
                <h4 class="box-title">@language.Getkey("Global_Add") @language.Getkey("Global_Individual")</h4>

                <div class="row">

                    <div class="col-md-2">
                        <input id="progressivo" name="progressivo" type="text" placeholder="@language.Getkey("Global_Progressive")">
                        <input id="idpercorso" name="idpercorso" type="hidden" value="@Model.id">
                    </div>
                    <div class="col-md-1">
                        <button type="submit" id="cerca" class="pbSubmit btn  btn-success btn-rounded btn-sm">@language.Getkey("Global_Search")</button>

                    </div>

                </div>

                <div class="row" id="risultato2">
                </div>





            </div>
        </div>
    </div>
</div>
@section Styles {


}

@section CustomStyles {
    <style>
        .ui-autocomplete {
            margin: 0px;
            font-family: Arial, Verdana, Sans-Serif;
            float: left;
            width: 10%;
            list-style-type: none;
            color: #0060B6;
            text-decoration: none;
        }

            .ui-autocomplete .fixed-height {
                float: left;
                max-height: 175px;
                overflow: auto !important;
                list-style-type: none;
            }

                .ui-autocomplete .fixed-height li {
                    font-family: Arial, Verdana, Sans-Serif;
                    float: left;
                    width: 100%;
                    list-style-type: none;
                    text-align: left;
                    font: bold 26px Poiret One;
                    list-style-type: none;
                }

            /* to distinctly see which returned item is selected/hovered over*/
            .ui-autocomplete .ui-menu-item .ui-corner-all {
                float: left;
                width: 100%;
                height: 30px;
                padding: 10px 0 10px 0;
                background: #FFF;
                list-style-type: none;
            }

            /* to hide the lower left text*/
            .ui-autocomplete .ui-menu-item .ui-state-focus {
                list-style-type: none;
                background-color: #00F;
                cursor: pointer;
            }

        .zoom {
            padding: 0px;
            transition: transform .2s; /* Animation */
            width: 50px;
            height: 50px;
            margin: 0 auto;
        }

            .zoom:hover {
                transform: scale(3.5); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
            }
    </style>


}
@section Scripts {


    <script src="~/js/datatables.min.js"></script>

}
@section CustomScripts {


    <script type="text/javascript">
        function CancellaIndividuoPercorso(x) {
            var url = $('#' + x).data('url');
            $.get(url, function (data) {
                $('#' + x).html(data);
                $('#' + x).modal({ backdrop: "static" });
            });
        }
    </script>

    <script type="text/javascript">
               $(document).ready(function () {
                       // Set the language for DataTables based on the ViewBag.lang value
                   var lingua = "@ViewBag.lang";
                  if (lingua == "en-US"){
                      $.extend($.fn.dataTable.defaults, {
                      language: { url: "/js/dataTables.english.json" }
                      });
                  } else {
                      $.extend($.fn.dataTable.defaults, {
                      language: { url: "/js/dataTables.default.json" }
                      });
                  }


                   var baseUrlauto = '@Url.Action("AutoComplete", "Percorsi")';


                   $("#progressivo").autocomplete({
                    source: function(request, response) {
                       $.ajax({
                       url: baseUrlauto,
                       dataType: "json",
                      data: {
                           term : request.term,
                           field : "progressivo"
                       },
                       success: function(data) {
                            response(data);
                       }
                       });
                    }
                   });


               $('#table1').DataTable({
                   'paging': true,
                   'lengthChange': true,
                   'searching': true,
                   'info': true,
                   'autoWidth': false,
                   'ordering': true
               })
               $('#table1').DataTable().order([7, 'asc']).draw();



               });
               var baseUrlRicerca = '@Url.Action("Ricerca", "Percorsi")';

               $("#cerca").click(function () {
                   var prog = $('#progressivo').val();
                   var idpercorso = $('#idpercorso').val();
                   $.ajax({
                       type: "GET",

                       url: baseUrlRicerca,
                       data: {
                           'idpercorso': idpercorso,
                           'progressivo': prog
                       },
                       success: function (data) {
                   var  namesc = "@language.Getkey("Global_Scientific_Name")";
                var  oldprog = "@language.Getkey("Global_Old_Progressive")";
            var sector = "@language.Getkey("Global_Sector")";
              var coll = "@language.Getkey("Global_Collection")";
        var lab = "@language.Getkey("Global_Label")";
              var imgs = "@language.Getkey("Global_Images")";
                    var add = "@language.Getkey("Global_Add")";
                        var ind = "@language.Getkey("Global_Individual")";
                           var s = '<div class="col-sm-12"><table id="table1" class="table table-bordered table-striped dataTable">';
                                    s += '<thead><tr><th></th><th>Progressivo</th><th>'+oldprog+'</th><th>'+namesc+'</th><th>'+sector+'</th><th>'+coll+'</th><th>'+lab+'</th><th>'+imgs+'</th></tr></thead>';
                           s += '<tbody>';
                           for (var i = 0; i < data.length; i++) {
                               var per = data[i].idpercorso;
                               var indi = data[i].idindividuo;
                               var action = '@Url.Action("Inserisciindividuopercorso", "Percorsi")?percorso=' + per + '&individuo=' + indi;



                               s += '<tr><td><a href="'+action+'">';
                               s += ' <button class="btn btn-success btn-xs" title="'+add+ ' ' + ind+ '" onclick="window.location.href =' + action +'"><i class="fa-solid fa-plus"></i></button></a></td>';
                               s += '<td>' + data[i].progressivo + '</td>';

                               if (data[i].vecchioprogressivo == null) {
                                   s += '<td></td>';
                               } else {
                               s += '<td>' + data[i].vecchioprogressivo + '</td>';
                               }

                               s += '<td>' + data[i].nomescientifico + '</td>';
                               s += '<td>' + data[i].settore + '</td>';
                               s += '<td>' + data[i].collezione + '</td>';
                               s += '<td>' + data[i].cartellino + '</td>';
                               s += '<td>' + data[i].immagini + '</td></tr>';
                           }
                           if (i == 0) {
                               alert("Non ho trovato individui corrispondenti verificare e correggi");


                           }
                           s += '</tbody></table></div>';
                           $("#risultato2").html(s);
                       },
                       error: function (xhr, ajaxOptions, thrownError) {
                           alert('Error during process: \n' + xhr.responseText);
                       }

                   });
               });
    </script>

}

UPlant/Views/InterventiAlberi/Edit.cshtml
@model UPlant.Models.DB.InterventiAlberi

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Interventi Alberi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="individuo" class="control-label"></label>
                <select asp-for="individuo" class="form-control" asp-items="ViewBag.individuo"></select>
                <span asp-validation-for="individuo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataapertura" class="control-label"></label>
                <input asp-for="dataapertura" class="form-control" />
                <span asp-validation-for="dataapertura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="priorita" class="control-label"></label>
                <select asp-for="priorita" class="form-control" asp-items="ViewBag.priorita"></select>
                <span asp-validation-for="priorita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="intervento" class="control-label"></label>
                <select asp-for="intervento" class="form-control" asp-items="ViewBag.intervento"></select>
                <span asp-validation-for="intervento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fornitore" class="control-label"></label>
                <select asp-for="fornitore" class="form-control" asp-items="ViewBag.fornitore"></select>
                <span asp-validation-for="fornitore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="motivo" class="control-label"></label>
                <input asp-for="motivo" class="form-control" />
                <span asp-validation-for="motivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="esitointervento" class="control-label"></label>
                <input asp-for="esitointervento" class="form-control" />
                <span asp-validation-for="esitointervento" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="statoIntervento" /> @Html.DisplayNameFor(model => model.statoIntervento)
                </label>
            </div>

            <div class="form-group">
                <label asp-for="utenteapertura" class="control-label"></label>
                <select asp-for="utenteapertura" class="form-control" asp-items="ViewBag.utenteapertura"></select>
                <span asp-validation-for="utenteapertura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="utenteultimamodifica" class="control-label"></label>
                <select asp-for="utenteultimamodifica" class="form-control" asp-items="ViewBag.utenteultimamodifica"></select>
                <span asp-validation-for="utenteultimamodifica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}